/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SemPermissaoRouteImport } from './routes/sem-permissao'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AguardandoAtivacaoRouteImport } from './routes/aguardando-ativacao'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminPlanosRouteImport } from './routes/admin.planos'
import { Route as AdminOrganizacoesRouteImport } from './routes/admin.organizacoes'
import { Route as AdminComunicacoesRouteImport } from './routes/admin.comunicacoes'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as AdminAssinaturasRouteImport } from './routes/admin.assinaturas'
import { Route as AppVendasRouteImport } from './routes/_app/vendas'
import { Route as AppUsuariosRouteImport } from './routes/_app/usuarios'
import { Route as AppRelatoriosRouteImport } from './routes/_app/relatorios'
import { Route as AppReceitasRouteImport } from './routes/_app/receitas'
import { Route as AppProdutosRouteImport } from './routes/_app/produtos'
import { Route as AppFinanceiroRouteImport } from './routes/_app/financeiro'
import { Route as AppEventosRouteImport } from './routes/_app/eventos'
import { Route as AppEstoqueRouteImport } from './routes/_app/estoque'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppCampanhasRouteImport } from './routes/_app/campanhas'
import { Route as AppAvaliacoesRouteImport } from './routes/_app/avaliacoes'
import { Route as AppAgendaRouteImport } from './routes/_app/agenda'
import { Route as AppAcessosRouteImport } from './routes/_app/acessos'
import { Route as AppReceitasIndexRouteImport } from './routes/_app/receitas.index'
import { Route as AppProdutosIndexRouteImport } from './routes/_app/produtos.index'
import { Route as AppClientesIndexRouteImport } from './routes/_app/clientes.index'
import { Route as AppAvaliacoesIndexRouteImport } from './routes/_app/avaliacoes.index'
import { Route as AppReceitasNovoRouteImport } from './routes/_app/receitas.novo'
import { Route as AppProdutosNovoRouteImport } from './routes/_app/produtos.novo'
import { Route as AppProdutosImportarHerbalifeRouteImport } from './routes/_app/produtos.importar-herbalife'
import { Route as AppProdutosIdRouteImport } from './routes/_app/produtos.$id'
import { Route as AppClientesNovoRouteImport } from './routes/_app/clientes.novo'
import { Route as AppClientesIdRouteImport } from './routes/_app/clientes.$id'
import { Route as AppAvaliacoesNovaRouteImport } from './routes/_app/avaliacoes.nova'
import { Route as AppAvaliacoesIdRouteImport } from './routes/_app/avaliacoes.$id'
import { Route as AppUsuariosIdPermissoesRouteImport } from './routes/_app/usuarios.$id.permissoes'
import { Route as AppReceitasEditarIdRouteImport } from './routes/_app/receitas.editar.$id'
import { Route as AppProdutosEditarIdRouteImport } from './routes/_app/produtos.editar.$id'
import { Route as AppClientesEditarIdRouteImport } from './routes/_app/clientes.editar.$id'

const SemPermissaoRoute = SemPermissaoRouteImport.update({
  id: '/sem-permissao',
  path: '/sem-permissao',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AguardandoAtivacaoRoute = AguardandoAtivacaoRouteImport.update({
  id: '/aguardando-ativacao',
  path: '/aguardando-ativacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanosRoute = AdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizacoesRoute = AdminOrganizacoesRouteImport.update({
  id: '/organizacoes',
  path: '/organizacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComunicacoesRoute = AdminComunicacoesRouteImport.update({
  id: '/comunicacoes',
  path: '/comunicacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssinaturasRoute = AdminAssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => AdminRoute,
} as any)
const AppVendasRoute = AppVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppReceitasRoute = AppReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppEventosRoute = AppEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhasRoute = AppCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AppRoute,
} as any)
const AppAvaliacoesRoute = AppAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppAcessosRoute = AppAcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => AppRoute,
} as any)
const AppReceitasIndexRoute = AppReceitasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReceitasRoute,
} as any)
const AppProdutosIndexRoute = AppProdutosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProdutosRoute,
} as any)
const AppClientesIndexRoute = AppClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AppRoute,
} as any)
const AppAvaliacoesIndexRoute = AppAvaliacoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAvaliacoesRoute,
} as any)
const AppReceitasNovoRoute = AppReceitasNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppReceitasRoute,
} as any)
const AppProdutosNovoRoute = AppProdutosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppProdutosRoute,
} as any)
const AppProdutosImportarHerbalifeRoute =
  AppProdutosImportarHerbalifeRouteImport.update({
    id: '/importar-herbalife',
    path: '/importar-herbalife',
    getParentRoute: () => AppProdutosRoute,
  } as any)
const AppProdutosIdRoute = AppProdutosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProdutosRoute,
} as any)
const AppClientesNovoRoute = AppClientesNovoRouteImport.update({
  id: '/clientes/novo',
  path: '/clientes/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIdRoute = AppClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAvaliacoesNovaRoute = AppAvaliacoesNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AppAvaliacoesRoute,
} as any)
const AppAvaliacoesIdRoute = AppAvaliacoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAvaliacoesRoute,
} as any)
const AppUsuariosIdPermissoesRoute = AppUsuariosIdPermissoesRouteImport.update({
  id: '/$id/permissoes',
  path: '/$id/permissoes',
  getParentRoute: () => AppUsuariosRoute,
} as any)
const AppReceitasEditarIdRoute = AppReceitasEditarIdRouteImport.update({
  id: '/editar/$id',
  path: '/editar/$id',
  getParentRoute: () => AppReceitasRoute,
} as any)
const AppProdutosEditarIdRoute = AppProdutosEditarIdRouteImport.update({
  id: '/editar/$id',
  path: '/editar/$id',
  getParentRoute: () => AppProdutosRoute,
} as any)
const AppClientesEditarIdRoute = AppClientesEditarIdRouteImport.update({
  id: '/clientes/editar/$id',
  path: '/clientes/editar/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aguardando-ativacao': typeof AguardandoAtivacaoRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/portal': typeof PortalRoute
  '/sem-permissao': typeof SemPermissaoRoute
  '/acessos': typeof AppAcessosRoute
  '/agenda': typeof AppAgendaRoute
  '/avaliacoes': typeof AppAvaliacoesRouteWithChildren
  '/campanhas': typeof AppCampanhasRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/estoque': typeof AppEstoqueRoute
  '/eventos': typeof AppEventosRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/produtos': typeof AppProdutosRouteWithChildren
  '/receitas': typeof AppReceitasRouteWithChildren
  '/relatorios': typeof AppRelatoriosRoute
  '/usuarios': typeof AppUsuariosRouteWithChildren
  '/vendas': typeof AppVendasRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/comunicacoes': typeof AdminComunicacoesRoute
  '/admin/organizacoes': typeof AdminOrganizacoesRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/': typeof AdminIndexRoute
  '/avaliacoes/$id': typeof AppAvaliacoesIdRoute
  '/avaliacoes/nova': typeof AppAvaliacoesNovaRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/clientes/novo': typeof AppClientesNovoRoute
  '/produtos/$id': typeof AppProdutosIdRoute
  '/produtos/importar-herbalife': typeof AppProdutosImportarHerbalifeRoute
  '/produtos/novo': typeof AppProdutosNovoRoute
  '/receitas/novo': typeof AppReceitasNovoRoute
  '/avaliacoes/': typeof AppAvaliacoesIndexRoute
  '/clientes/': typeof AppClientesIndexRoute
  '/produtos/': typeof AppProdutosIndexRoute
  '/receitas/': typeof AppReceitasIndexRoute
  '/clientes/editar/$id': typeof AppClientesEditarIdRoute
  '/produtos/editar/$id': typeof AppProdutosEditarIdRoute
  '/receitas/editar/$id': typeof AppReceitasEditarIdRoute
  '/usuarios/$id/permissoes': typeof AppUsuariosIdPermissoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aguardando-ativacao': typeof AguardandoAtivacaoRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/portal': typeof PortalRoute
  '/sem-permissao': typeof SemPermissaoRoute
  '/acessos': typeof AppAcessosRoute
  '/agenda': typeof AppAgendaRoute
  '/campanhas': typeof AppCampanhasRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/estoque': typeof AppEstoqueRoute
  '/eventos': typeof AppEventosRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/usuarios': typeof AppUsuariosRouteWithChildren
  '/vendas': typeof AppVendasRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/comunicacoes': typeof AdminComunicacoesRoute
  '/admin/organizacoes': typeof AdminOrganizacoesRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin': typeof AdminIndexRoute
  '/avaliacoes/$id': typeof AppAvaliacoesIdRoute
  '/avaliacoes/nova': typeof AppAvaliacoesNovaRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/clientes/novo': typeof AppClientesNovoRoute
  '/produtos/$id': typeof AppProdutosIdRoute
  '/produtos/importar-herbalife': typeof AppProdutosImportarHerbalifeRoute
  '/produtos/novo': typeof AppProdutosNovoRoute
  '/receitas/novo': typeof AppReceitasNovoRoute
  '/avaliacoes': typeof AppAvaliacoesIndexRoute
  '/clientes': typeof AppClientesIndexRoute
  '/produtos': typeof AppProdutosIndexRoute
  '/receitas': typeof AppReceitasIndexRoute
  '/clientes/editar/$id': typeof AppClientesEditarIdRoute
  '/produtos/editar/$id': typeof AppProdutosEditarIdRoute
  '/receitas/editar/$id': typeof AppReceitasEditarIdRoute
  '/usuarios/$id/permissoes': typeof AppUsuariosIdPermissoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/aguardando-ativacao': typeof AguardandoAtivacaoRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/portal': typeof PortalRoute
  '/sem-permissao': typeof SemPermissaoRoute
  '/_app/acessos': typeof AppAcessosRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/avaliacoes': typeof AppAvaliacoesRouteWithChildren
  '/_app/campanhas': typeof AppCampanhasRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/estoque': typeof AppEstoqueRoute
  '/_app/eventos': typeof AppEventosRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/produtos': typeof AppProdutosRouteWithChildren
  '/_app/receitas': typeof AppReceitasRouteWithChildren
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/usuarios': typeof AppUsuariosRouteWithChildren
  '/_app/vendas': typeof AppVendasRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/comunicacoes': typeof AdminComunicacoesRoute
  '/admin/organizacoes': typeof AdminOrganizacoesRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/avaliacoes/$id': typeof AppAvaliacoesIdRoute
  '/_app/avaliacoes/nova': typeof AppAvaliacoesNovaRoute
  '/_app/clientes/$id': typeof AppClientesIdRoute
  '/_app/clientes/novo': typeof AppClientesNovoRoute
  '/_app/produtos/$id': typeof AppProdutosIdRoute
  '/_app/produtos/importar-herbalife': typeof AppProdutosImportarHerbalifeRoute
  '/_app/produtos/novo': typeof AppProdutosNovoRoute
  '/_app/receitas/novo': typeof AppReceitasNovoRoute
  '/_app/avaliacoes/': typeof AppAvaliacoesIndexRoute
  '/_app/clientes/': typeof AppClientesIndexRoute
  '/_app/produtos/': typeof AppProdutosIndexRoute
  '/_app/receitas/': typeof AppReceitasIndexRoute
  '/_app/clientes/editar/$id': typeof AppClientesEditarIdRoute
  '/_app/produtos/editar/$id': typeof AppProdutosEditarIdRoute
  '/_app/receitas/editar/$id': typeof AppReceitasEditarIdRoute
  '/_app/usuarios/$id/permissoes': typeof AppUsuariosIdPermissoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aguardando-ativacao'
    | '/login'
    | '/onboarding'
    | '/portal'
    | '/sem-permissao'
    | '/acessos'
    | '/agenda'
    | '/avaliacoes'
    | '/campanhas'
    | '/configuracoes'
    | '/dashboard'
    | '/estoque'
    | '/eventos'
    | '/financeiro'
    | '/produtos'
    | '/receitas'
    | '/relatorios'
    | '/usuarios'
    | '/vendas'
    | '/admin/assinaturas'
    | '/admin/auditoria'
    | '/admin/comunicacoes'
    | '/admin/organizacoes'
    | '/admin/planos'
    | '/admin/'
    | '/avaliacoes/$id'
    | '/avaliacoes/nova'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/produtos/$id'
    | '/produtos/importar-herbalife'
    | '/produtos/novo'
    | '/receitas/novo'
    | '/avaliacoes/'
    | '/clientes/'
    | '/produtos/'
    | '/receitas/'
    | '/clientes/editar/$id'
    | '/produtos/editar/$id'
    | '/receitas/editar/$id'
    | '/usuarios/$id/permissoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aguardando-ativacao'
    | '/login'
    | '/onboarding'
    | '/portal'
    | '/sem-permissao'
    | '/acessos'
    | '/agenda'
    | '/campanhas'
    | '/configuracoes'
    | '/dashboard'
    | '/estoque'
    | '/eventos'
    | '/financeiro'
    | '/relatorios'
    | '/usuarios'
    | '/vendas'
    | '/admin/assinaturas'
    | '/admin/auditoria'
    | '/admin/comunicacoes'
    | '/admin/organizacoes'
    | '/admin/planos'
    | '/admin'
    | '/avaliacoes/$id'
    | '/avaliacoes/nova'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/produtos/$id'
    | '/produtos/importar-herbalife'
    | '/produtos/novo'
    | '/receitas/novo'
    | '/avaliacoes'
    | '/clientes'
    | '/produtos'
    | '/receitas'
    | '/clientes/editar/$id'
    | '/produtos/editar/$id'
    | '/receitas/editar/$id'
    | '/usuarios/$id/permissoes'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/aguardando-ativacao'
    | '/login'
    | '/onboarding'
    | '/portal'
    | '/sem-permissao'
    | '/_app/acessos'
    | '/_app/agenda'
    | '/_app/avaliacoes'
    | '/_app/campanhas'
    | '/_app/configuracoes'
    | '/_app/dashboard'
    | '/_app/estoque'
    | '/_app/eventos'
    | '/_app/financeiro'
    | '/_app/produtos'
    | '/_app/receitas'
    | '/_app/relatorios'
    | '/_app/usuarios'
    | '/_app/vendas'
    | '/admin/assinaturas'
    | '/admin/auditoria'
    | '/admin/comunicacoes'
    | '/admin/organizacoes'
    | '/admin/planos'
    | '/admin/'
    | '/_app/avaliacoes/$id'
    | '/_app/avaliacoes/nova'
    | '/_app/clientes/$id'
    | '/_app/clientes/novo'
    | '/_app/produtos/$id'
    | '/_app/produtos/importar-herbalife'
    | '/_app/produtos/novo'
    | '/_app/receitas/novo'
    | '/_app/avaliacoes/'
    | '/_app/clientes/'
    | '/_app/produtos/'
    | '/_app/receitas/'
    | '/_app/clientes/editar/$id'
    | '/_app/produtos/editar/$id'
    | '/_app/receitas/editar/$id'
    | '/_app/usuarios/$id/permissoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AguardandoAtivacaoRoute: typeof AguardandoAtivacaoRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PortalRoute: typeof PortalRoute
  SemPermissaoRoute: typeof SemPermissaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sem-permissao': {
      id: '/sem-permissao'
      path: '/sem-permissao'
      fullPath: '/sem-permissao'
      preLoaderRoute: typeof SemPermissaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aguardando-ativacao': {
      id: '/aguardando-ativacao'
      path: '/aguardando-ativacao'
      fullPath: '/aguardando-ativacao'
      preLoaderRoute: typeof AguardandoAtivacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planos': {
      id: '/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminPlanosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizacoes': {
      id: '/admin/organizacoes'
      path: '/organizacoes'
      fullPath: '/admin/organizacoes'
      preLoaderRoute: typeof AdminOrganizacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comunicacoes': {
      id: '/admin/comunicacoes'
      path: '/comunicacoes'
      fullPath: '/admin/comunicacoes'
      preLoaderRoute: typeof AdminComunicacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assinaturas': {
      id: '/admin/assinaturas'
      path: '/assinaturas'
      fullPath: '/admin/assinaturas'
      preLoaderRoute: typeof AdminAssinaturasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/vendas': {
      id: '/_app/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AppVendasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receitas': {
      id: '/_app/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof AppReceitasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produtos': {
      id: '/_app/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/eventos': {
      id: '/_app/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof AppEventosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque': {
      id: '/_app/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campanhas': {
      id: '/_app/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof AppCampanhasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/avaliacoes': {
      id: '/_app/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof AppAvaliacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/acessos': {
      id: '/_app/acessos'
      path: '/acessos'
      fullPath: '/acessos'
      preLoaderRoute: typeof AppAcessosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receitas/': {
      id: '/_app/receitas/'
      path: '/'
      fullPath: '/receitas/'
      preLoaderRoute: typeof AppReceitasIndexRouteImport
      parentRoute: typeof AppReceitasRoute
    }
    '/_app/produtos/': {
      id: '/_app/produtos/'
      path: '/'
      fullPath: '/produtos/'
      preLoaderRoute: typeof AppProdutosIndexRouteImport
      parentRoute: typeof AppProdutosRoute
    }
    '/_app/clientes/': {
      id: '/_app/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AppClientesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/avaliacoes/': {
      id: '/_app/avaliacoes/'
      path: '/'
      fullPath: '/avaliacoes/'
      preLoaderRoute: typeof AppAvaliacoesIndexRouteImport
      parentRoute: typeof AppAvaliacoesRoute
    }
    '/_app/receitas/novo': {
      id: '/_app/receitas/novo'
      path: '/novo'
      fullPath: '/receitas/novo'
      preLoaderRoute: typeof AppReceitasNovoRouteImport
      parentRoute: typeof AppReceitasRoute
    }
    '/_app/produtos/novo': {
      id: '/_app/produtos/novo'
      path: '/novo'
      fullPath: '/produtos/novo'
      preLoaderRoute: typeof AppProdutosNovoRouteImport
      parentRoute: typeof AppProdutosRoute
    }
    '/_app/produtos/importar-herbalife': {
      id: '/_app/produtos/importar-herbalife'
      path: '/importar-herbalife'
      fullPath: '/produtos/importar-herbalife'
      preLoaderRoute: typeof AppProdutosImportarHerbalifeRouteImport
      parentRoute: typeof AppProdutosRoute
    }
    '/_app/produtos/$id': {
      id: '/_app/produtos/$id'
      path: '/$id'
      fullPath: '/produtos/$id'
      preLoaderRoute: typeof AppProdutosIdRouteImport
      parentRoute: typeof AppProdutosRoute
    }
    '/_app/clientes/novo': {
      id: '/_app/clientes/novo'
      path: '/clientes/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof AppClientesNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/$id': {
      id: '/_app/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AppClientesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/avaliacoes/nova': {
      id: '/_app/avaliacoes/nova'
      path: '/nova'
      fullPath: '/avaliacoes/nova'
      preLoaderRoute: typeof AppAvaliacoesNovaRouteImport
      parentRoute: typeof AppAvaliacoesRoute
    }
    '/_app/avaliacoes/$id': {
      id: '/_app/avaliacoes/$id'
      path: '/$id'
      fullPath: '/avaliacoes/$id'
      preLoaderRoute: typeof AppAvaliacoesIdRouteImport
      parentRoute: typeof AppAvaliacoesRoute
    }
    '/_app/usuarios/$id/permissoes': {
      id: '/_app/usuarios/$id/permissoes'
      path: '/$id/permissoes'
      fullPath: '/usuarios/$id/permissoes'
      preLoaderRoute: typeof AppUsuariosIdPermissoesRouteImport
      parentRoute: typeof AppUsuariosRoute
    }
    '/_app/receitas/editar/$id': {
      id: '/_app/receitas/editar/$id'
      path: '/editar/$id'
      fullPath: '/receitas/editar/$id'
      preLoaderRoute: typeof AppReceitasEditarIdRouteImport
      parentRoute: typeof AppReceitasRoute
    }
    '/_app/produtos/editar/$id': {
      id: '/_app/produtos/editar/$id'
      path: '/editar/$id'
      fullPath: '/produtos/editar/$id'
      preLoaderRoute: typeof AppProdutosEditarIdRouteImport
      parentRoute: typeof AppProdutosRoute
    }
    '/_app/clientes/editar/$id': {
      id: '/_app/clientes/editar/$id'
      path: '/clientes/editar/$id'
      fullPath: '/clientes/editar/$id'
      preLoaderRoute: typeof AppClientesEditarIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAvaliacoesRouteChildren {
  AppAvaliacoesIdRoute: typeof AppAvaliacoesIdRoute
  AppAvaliacoesNovaRoute: typeof AppAvaliacoesNovaRoute
  AppAvaliacoesIndexRoute: typeof AppAvaliacoesIndexRoute
}

const AppAvaliacoesRouteChildren: AppAvaliacoesRouteChildren = {
  AppAvaliacoesIdRoute: AppAvaliacoesIdRoute,
  AppAvaliacoesNovaRoute: AppAvaliacoesNovaRoute,
  AppAvaliacoesIndexRoute: AppAvaliacoesIndexRoute,
}

const AppAvaliacoesRouteWithChildren = AppAvaliacoesRoute._addFileChildren(
  AppAvaliacoesRouteChildren,
)

interface AppProdutosRouteChildren {
  AppProdutosIdRoute: typeof AppProdutosIdRoute
  AppProdutosImportarHerbalifeRoute: typeof AppProdutosImportarHerbalifeRoute
  AppProdutosNovoRoute: typeof AppProdutosNovoRoute
  AppProdutosIndexRoute: typeof AppProdutosIndexRoute
  AppProdutosEditarIdRoute: typeof AppProdutosEditarIdRoute
}

const AppProdutosRouteChildren: AppProdutosRouteChildren = {
  AppProdutosIdRoute: AppProdutosIdRoute,
  AppProdutosImportarHerbalifeRoute: AppProdutosImportarHerbalifeRoute,
  AppProdutosNovoRoute: AppProdutosNovoRoute,
  AppProdutosIndexRoute: AppProdutosIndexRoute,
  AppProdutosEditarIdRoute: AppProdutosEditarIdRoute,
}

const AppProdutosRouteWithChildren = AppProdutosRoute._addFileChildren(
  AppProdutosRouteChildren,
)

interface AppReceitasRouteChildren {
  AppReceitasNovoRoute: typeof AppReceitasNovoRoute
  AppReceitasIndexRoute: typeof AppReceitasIndexRoute
  AppReceitasEditarIdRoute: typeof AppReceitasEditarIdRoute
}

const AppReceitasRouteChildren: AppReceitasRouteChildren = {
  AppReceitasNovoRoute: AppReceitasNovoRoute,
  AppReceitasIndexRoute: AppReceitasIndexRoute,
  AppReceitasEditarIdRoute: AppReceitasEditarIdRoute,
}

const AppReceitasRouteWithChildren = AppReceitasRoute._addFileChildren(
  AppReceitasRouteChildren,
)

interface AppUsuariosRouteChildren {
  AppUsuariosIdPermissoesRoute: typeof AppUsuariosIdPermissoesRoute
}

const AppUsuariosRouteChildren: AppUsuariosRouteChildren = {
  AppUsuariosIdPermissoesRoute: AppUsuariosIdPermissoesRoute,
}

const AppUsuariosRouteWithChildren = AppUsuariosRoute._addFileChildren(
  AppUsuariosRouteChildren,
)

interface AppRouteChildren {
  AppAcessosRoute: typeof AppAcessosRoute
  AppAgendaRoute: typeof AppAgendaRoute
  AppAvaliacoesRoute: typeof AppAvaliacoesRouteWithChildren
  AppCampanhasRoute: typeof AppCampanhasRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppEventosRoute: typeof AppEventosRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppProdutosRoute: typeof AppProdutosRouteWithChildren
  AppReceitasRoute: typeof AppReceitasRouteWithChildren
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppUsuariosRoute: typeof AppUsuariosRouteWithChildren
  AppVendasRoute: typeof AppVendasRoute
  AppClientesIdRoute: typeof AppClientesIdRoute
  AppClientesNovoRoute: typeof AppClientesNovoRoute
  AppClientesIndexRoute: typeof AppClientesIndexRoute
  AppClientesEditarIdRoute: typeof AppClientesEditarIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcessosRoute: AppAcessosRoute,
  AppAgendaRoute: AppAgendaRoute,
  AppAvaliacoesRoute: AppAvaliacoesRouteWithChildren,
  AppCampanhasRoute: AppCampanhasRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEstoqueRoute: AppEstoqueRoute,
  AppEventosRoute: AppEventosRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppProdutosRoute: AppProdutosRouteWithChildren,
  AppReceitasRoute: AppReceitasRouteWithChildren,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppUsuariosRoute: AppUsuariosRouteWithChildren,
  AppVendasRoute: AppVendasRoute,
  AppClientesIdRoute: AppClientesIdRoute,
  AppClientesNovoRoute: AppClientesNovoRoute,
  AppClientesIndexRoute: AppClientesIndexRoute,
  AppClientesEditarIdRoute: AppClientesEditarIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminAssinaturasRoute: typeof AdminAssinaturasRoute
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminComunicacoesRoute: typeof AdminComunicacoesRoute
  AdminOrganizacoesRoute: typeof AdminOrganizacoesRoute
  AdminPlanosRoute: typeof AdminPlanosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAssinaturasRoute: AdminAssinaturasRoute,
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminComunicacoesRoute: AdminComunicacoesRoute,
  AdminOrganizacoesRoute: AdminOrganizacoesRoute,
  AdminPlanosRoute: AdminPlanosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AguardandoAtivacaoRoute: AguardandoAtivacaoRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PortalRoute: PortalRoute,
  SemPermissaoRoute: SemPermissaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
